"""First migration

Revision ID: 7992a23eaea8
Revises: 
Create Date: 2023-10-04 15:23:03.285963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7992a23eaea8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('plan_number', sa.String(), nullable=False),
    sa.Column('subscriber', sa.Integer(), nullable=False),
    sa.Column('provider_npi', sa.BigInteger(), nullable=False),
    sa.Column('service_date', sa.String(), nullable=False),
    sa.Column('submitted_procedure', sa.String(), nullable=False),
    sa.Column('quadrant', sa.String(), nullable=True),
    sa.Column('plan_number', sa.String(), nullable=False),
    sa.Column('provider_fees', sa.Integer(), nullable=False),
    sa.Column('allowed_fees', sa.Integer(), nullable=False),
    sa.Column('member_coinsurance', sa.Integer(), nullable=False),
    sa.Column('member_copay', sa.Integer(), nullable=False),
    sa.Column('net_fees', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_details_id'), 'claim_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_details_id'), table_name='claim_details')
    op.drop_table('claim_details')
    # ### end Alembic commands ###
